Adding Thor to coconut, so it can be an executable gem
andresgap/coconut pull request #4
Opened 2016-10-24 14:11 UTC by royGap

2016-10-24 14:27 UTC, royGap commented on lib/coconut.rb
> +# module Coconut
remove this comments

2016-10-24 14:27 UTC, royGap commented on lib/coconut/version.rb
> +VERSION = "0.1.0"
bump the version to 0.1.1

2016-10-24 14:27 UTC, royGap commented on lib/generators/coconut/templates/coconut.tt
> +  customer_path: customers
remove this element is no longer needed

2016-10-24 16:29 UTC, jpaparra requested changes

2016-10-24 16:29 UTC, jparragap commented on README.md
> +```Init a coconut instanca
instance*

2016-10-24 16:29 UTC, jparragap commented on lib/coconut/cache_service.rb
> +  TMP_PATH = "./tmp"
single quotes

2016-10-24 16:42 UTC, andresgap commented on lib/coconut/commands/fetch.rb
> +module Commands
Does commands represent the class? Seems to generic

2016-10-24 16:42 UTC, andresgap commented on lib/generators/init_file.rb
> +    desc 'Generate configuration to init a coconut instance on a SQ proyect'
Remove any referece to SQ or D360

2016-10-24 16:42 UTC, andresgap commented on bin/coconut
> +  desc "init", "init a SQ project with a coconut instance"
Same here

2018-02-13 20:22 UTC, jpaparra commented on lib/coconut/cli.rb
> +    desc "install", "install the coconut on the local enviroment"
Use single quotes

2018-03-08 01:57 UTC, andresgap commented on lib/generators/coconut/templates/coconut.tt
> -
Please remove anything related to specific server configurations, like these file names or paths

2018-08-26 03:12 UTC, merged